# Generated by Django 4.1.1 on 2022-09-26 11:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "spotify_uri",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "spotify_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_non_spotify", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="HitList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("vote_start_date", models.DateTimeField()),
                ("vote_end_date", models.DateTimeField()),
                ("is_closed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "spotify_uri",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "preview_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "spotify_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "image_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_non_spotify", models.BooleanField(default=False)),
                ("artists", models.ManyToManyField(to="core.artist")),
            ],
        ),
        migrations.CreateModel(
            name="VoteSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("submitter_name", models.CharField(max_length=255)),
                ("is_invalidated", models.BooleanField(default=False)),
                (
                    "timestamp",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                (
                    "hit_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.hitlist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("points", models.PositiveIntegerField()),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.votesubmission",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.track",
                    ),
                ),
            ],
        ),
    ]
