# Generated by Django 4.1.4 on 2023-01-11 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_hitlist_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HitListSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_hitlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.hitlist",
                    ),
                ),
            ],
        ),
    ]
